---
name: Release
on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-python@v5
      - run: pip install -r requirements-dev.txt

      - name: Build Assets
        run: python setup.py sdist bdist_wheel

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Version ${{ github.ref_name }}"
          generate_release_notes: true
          files: |
            dist/*
