---
name: Release
on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5 # v5

      - name: Setup Python
        uses: actions/setup-python@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Build Release
        run: uv build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Version ${{ github.ref_name }}"
          files: |
            dist/*
