---
name: Release
on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - uses: actions/setup-python@v5
      - run: pip install -r requirements-dev.txt

      - name: Build Assets
        run: python setup.py sdist bdist_wheel

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Version ${{ github.ref_name }}"
          generate_release_notes: true
          files: |
            dist/*
